pipeline {
    agent any
     parameters {
        string(defaultValue: "", description: 'What environment?', name: 'Environment')
        // choices are newline separated
        choice(choices: 'US-EAST-1\nUS-WEST-2', description: 'What AWS region?', name: 'region')
    }
    tools {
        maven 'Jenkins_Maven'
        //jdk 'Your JDK Name'
    }
    stages {
        stage ('Checkout'){
            steps 
            {
                git (
                    url: 'https://github.com/sbsv/DevOps_Repo.git',
                    credentialsId: 'e36633b2-ceae-4ac4-bd30-23e96432f61c'
                )
            }
            
            }
    }
}
